## Initial Review

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import datetime as dt

In [28]:
fin_df = pd.read_excel(r'D:\Workspace\Projects\AI_ML\behavioural-finance-analyser\data\raw\personal finance data.xlsx')
display(fin_df.head())

,Date / Time,Mode,Category,Sub category,Income/Expense,Debit/Credit
0,2021-01-01 21:45:00,CUB - online payment,Allowance,From dad,Income,8000.0
1,2021-01-01 21:46:00,CUB - online payment,Food,Snacks,Expense,85.0
2,2021-01-03 18:21:00,CUB - online payment,Other,From dad,Income,500.0
3,2021-01-03 18:22:00,CUB - online payment,Household,Stuffs,Expense,6667.0
4,2021-01-03 18:56:00,CUB - online payment,Transportation,Metro,Expense,30.0

In [29]:
fin_df.dtypes

Date / Time       datetime64[us]
Mode                         str
Category                     str
Sub category                 str
Income/Expense               str
Debit/Credit             float64
dtype: object

In [30]:
import datetime as dt

fin_df['Date'] = fin_df['Date / Time'].dt.date
fin_df['Time'] = fin_df['Date / Time'].dt.time

# delete the column and shift date and time at the start

fin_df = fin_df.drop(columns=['Date / Time'])

cols = ['Date', 'Time'] + [col for col in fin_df.columns if col not in ['Date', 'Time']]
fin_df = fin_df[cols]

#rename columsn for easy access
fin_df  = fin_df.rename(columns={
    'Income/Expense' : 'transaction_type',
    'Debit/Credit' : 'ledger_type'
})

In [31]:
fin_df.head()

,Date,Time,Mode,Category,Sub category,transaction_type,ledger_type
0,2021-01-01,21:45:00,CUB - online payment,Allowance,From dad,Income,8000.0
1,2021-01-01,21:46:00,CUB - online payment,Food,Snacks,Expense,85.0
2,2021-01-03,18:21:00,CUB - online payment,Other,From dad,Income,500.0
3,2021-01-03,18:22:00,CUB - online payment,Household,Stuffs,Expense,6667.0
4,2021-01-03,18:56:00,CUB - online payment,Transportation,Metro,Expense,30.0